# Generated by Django 4.2.6 on 2023-10-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя/Псевдоним/Название исполнителя')),
                ('original_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя/Псевдоним/Название исполнителя на оригинальном языке')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Английское Имя/Псевдоним/Название исполнителя')),
                ('alternative_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Альтернативное Имя/Псевдоним/Название исполнителя')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уникальный slug исполнителя')),
                ('searchstring', models.CharField(blank=True, max_length=500, null=True, verbose_name='Специальное поле, используемое при поиске')),
                ('is_favorite', models.PositiveSmallIntegerField(default=0, verbose_name='Избранное')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.country', to_field='code', verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название на оригинальном языке')),
                ('english_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название на английском языке')),
                ('romanized_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Романизированное название')),
                ('alternative_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Альтернативное название')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Грейд')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер песни в альбоме')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('sorting_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Служебное название для сортировки')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_set', to='musicstation.album', verbose_name='Альбом')),
                ('artist_set', models.ManyToManyField(blank=True, related_name='song_set_as_featuring_artist', to='musicstation.artist', verbose_name='Исполнители')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lib.language', to_field='code', verbose_name='Язык')),
                ('main_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_set', to='musicstation.artist', verbose_name='Основной исполнитель')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_set', to='musicstation.artist', verbose_name='Исполнитель'),
        ),
    ]
